import Head from 'next/head';
import Router from 'next/router';
import { useEffect, useState } from 'react';
import { getAuth, onAuthStateChanged, signOut } from 'firebase/auth';
import styles from '../styles/Tosso.module.css';
import TossoOperations from '../src/components/TossoOperations';
import TossoDetails from '../src/components/TossoDetails';

const Tosso = () => {
	// TossoOperation에 있는 문서들 아이디 담을 스테이트
	const [id, setId] = useState(null);
	// 프롭스로 전달할 함수
	// TossoOperation에서 각 문서 id를 보내면 id변수에다 저장
	function getSingleTosso(id) {
		setId(id);
	}

	const [logined, setLogined] = useState(false);
	const [email, setEmail] = useState('');

	const auth = getAuth();

	const logout = async () => {
		try {
			await signOut(auth);
			return Router.push({
				pathname: '/',
			});
		} catch (err) {
			return console.log(err);
		}
	};

	useEffect(() => {
		onAuthStateChanged(auth, (user) => {
			if (user) {
				setEmail(user.email);
				return setLogined(true);
			}
			return Router.push({
				pathname: '/login',
			});
		});
	}, [auth.currentUser]);

	return (
		<div className={styles.container}>
			{logined ? (
				<div>
					<Head>
						<title>Create Tosso App</title>
						<meta
							name="description"
							content="Generated by create tosso app"
						/>
						<link rel="icon" href="/favicon.ico" />
					</Head>

					<main>
						<div className={styles.container}>
							<div className={styles.left}>
								{/* getSingleTosso를 동일명으로 TossoOperation에 프롭스전달 */}
								<TossoOperations
									getSingleTosso={getSingleTosso}
									email={email}
								/>
							</div>
							<div className={styles.right}>
								{/* 또 마찬가지로 id를 TossoDetails에 프롭스전달 */}
								<TossoDetails id={id} />
							</div>
						</div>
						<button onClick={logout}>로그아웃</button>
					</main>
				</div>
			) : (
				<div />
			)}
		</div>
	);
};

export default Tosso;
